config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get 'portfolio' => 'pages#portfolio'
  get 'home' => 'pages#welcome'
  get 'contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
  
  def contact
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

</head>
<body>

<div class="header">
  <div class="container">
    <ul class="pull-right">
      <li><%= link_to "Welcome", home_path %></li>
      <li><%= link_to "Portfolio", portfolio_path %></li>
      <li><%= link_to "Contact" , contact_path %></li>
    </ul>
  </div>
</div>

<%= yield %>

<div class="footer">
  <div class="container">
    <ul class="pull-left">
      <%= link_to "© 2015 Quan Tran", contact_path %>
    </ul>
    <ul class="pull-right">
      <p>Share this page</p>
      <a href="#"><img src="https://s3-eu5.ixquick.com/cgi-bin/serveimage?url=http%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Ma1a43ad8bd475eb8b117e00a1a0a90a0o0%26pid%3D15.1%26f%3D1&sp=94eec8ac58b0eaeb75edc7b064f32e3b" width = "50"></a>
      <a href="#"><img src="https://s3-eu5.ixquick.com/cgi-bin/serveimage?url=http%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.M6f2455fecb9cf51564c7b58b057d723bH0%26pid%3D15.1%26f%3D1&sp=6631418fb0b7dd67eaf83022b84648be" width = "50"></a>
      <a href="#"><img src="https://s15-us2.ixquick.com/cgi-bin/serveimage?url=http%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.M769b2f2929515498d08cce4f5941960co0%26pid%3D15.1%26f%3D1&sp=4a003c10f37daf6128400e7bc3feb0ce" width = "50"></a>
    </ul>
  </div>
</div>
</body>
</html>

app/views/pages/contact.html.erb
<div class="main">
  <div class="container">
    <ul>
      <div>Bello, nothing to see here.</div>
      <img src="https://s17-us2.ixquick.com/cgi-bin/serveimage?url=http%3A%2F%2Fimg-new.cgtrader.com%2Fitems%2F67046%2Flarge_minion_baby_3d_model_max_d44b57c6-87e7-4e1f-bd25-0e78bab8c537.jpg&sp=7ee4707165fc5183eef5003c690dc736" height="400">
    </ul>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div class="banner">
    <ul>
      <li><img src="http://gdurl.com/DpQm"</li>
      <li><img src="http://gdurl.com/2FcB"</li>
      <li><img src="http://gdurl.com/yvL9"</li>
      <li><img src="http://gdurl.com/DkKM"</li>
    </ul>
  </div>

<script>
	if(window.chrome) {
		$('.banner li').css('background-size', '100% 100%');
	}
			
	$('.banner').unslider({
		fluid: true,
		dots: true,
		speed: 500
	});
		
	//  Find any element starting with a # in the URL
	//  And listen to any click events it fires
	$('a[href^="#"]').click(function() {
		//  Find the target element
		var target = $($(this).attr('href'));
				
		//  And get its position
		var pos = target.offset(); // fallback to scrolling to top || {left: 0, top: 0};
				
		//  jQuery will return false if there's no element
		//  and your code will throw errors if it tries to do .offset().left;
		if(pos) {
			//  Scroll the page
			$('html, body').animate({
				scrollTop: pos.top,
				scrollLeft: pos.left
			}, 1000);
		}
				
		//  Don't let them visit the url, we'll scroll you there
		return false;
	});
</script>

app/views/pages/welcome.html.erb
<div class="main">
  <div class="container">
    <ul>
    <h2>Quan Tran</h2>
    <img src="https://s17-us2.ixquick.com/cgi-bin/serveimage?url=http%3A%2F%2Fimg-new.cgtrader.com%2Fitems%2F67046%2Flarge_minion_baby_3d_model_max_d44b57c6-87e7-4e1f-bd25-0e78bab8c537.jpg&sp=7ee4707165fc5183eef5003c690dc736" width="250"><br>
      <%= link_to 'View my work', portfolio_path %>
    </ul>
    <div class="proverb">
      <h1>If you want to walk fast, walk alone; but if you want to walk far, walk together</h1>
      <h3 class="source">An African proverb</h3>
  </div>
</div>